name: Build-Mac

on: [push, pull_request]

jobs:
  build-macos:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update brew and install dependencies
      run: brew update && brew install boost hidapi zmq libpgm unbound libsodium miniupnpc ldns expat libunwind-headers protobuf qt5 
    - name: build
      run: export PATH=$PATH:/usr/local/opt/qt/bin && ./build.sh
    - name: test qml
      run: build/release/bin/swap-wallet-gui.app/Contents/MacOS/swap-wallet-gui --test-qml
